### PR TITLE
first pull request

### PR DESCRIPTION
**Pull request by Chingiz**
Please check the codes and accept pull request. I made minimal customizations that can be helpful for your project.

### CODE REVIEW

**Comment by ziyaddin** [comment]
What is the need of change of css codes? I couldn't understand. I can't see any change in result. If there is, let me know. Thank you for pull request!

**Comment by Chingiz** [comment]
then why did u merge?

**Comment by ziyaddin** [comment]
Then why did you made a pull request if it is not important?

**Comment by Chingiz** [comment]
let's not hurt each other 😈

**Comment by ziyaddin** [comment]
agree :tulip:

**Pull request merged**
